name: kanban
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./server
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/kanban
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8000:8000"]

  web:
    build: ./client
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    ports: ["5173:5173"]

volumes:
  pgdata: