[tool.ruff]
target-version = "py311"
line-length = 100

src = ["app"]

exclude = [
    ".git", ".hg", ".mypy_cache", ".ruff_cache", ".tox",
    ".venv", "venv", "__pycache__", "build", "dist", "node_modules"
]
respect-gitignore = true

[tool.ruff.lint]
select = ["E","F","I","B","UP","SIM","C4","RUF"]
ignore = []

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
